# Generated by Django 5.2.11 on 2026-04-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
