# Generated by Django 6.0.3 on 2026-04-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_app', '0002_timeslot_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='is_lab',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subject',
            name='credits',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_lab',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subject',
            name='lab_duration',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='subject',
            name='weekly_lab_sessions',
            field=models.IntegerField(default=1),
        ),
    ]
