# Generated by Django 6.0.3 on 2026-04-25 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_app', '0003_classroom_is_lab_subject_credits_subject_is_lab_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='weekly_lab_sessions',
            new_name='lab_credit',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='faculty',
        ),
        migrations.AddField(
            model_name='timetable',
            name='faculty',
            field=models.ManyToManyField(related_name='timetables', to='timetable_app.faculty'),
        ),
    ]
