# Generated by Django 6.0.3 on 2026-04-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_app', '0004_rename_weekly_lab_sessions_subject_lab_credit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='lab_credit',
        ),
        migrations.AddField(
            model_name='subject',
            name='lectures_per_week',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='weekly_lab_sessions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='capacity',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='room_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='faculty',
            field=models.ManyToManyField(to='timetable_app.faculty'),
        ),
    ]
