# Generated by Django 6.0.3 on 2026-05-07 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_app', '0006_alter_faculty_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='is_break',
            field=models.BooleanField(default=False),
        ),
    ]
