# Generated by Django 6.0.3 on 2026-05-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_app', '0007_timeslot_is_break'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='shift',
            field=models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon')], default='morning', max_length=20),
        ),
    ]
