# Generated by Django 6.0.3 on 2026-05-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_app', '0008_timeslot_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='shift',
            field=models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon')], max_length=20),
        ),
    ]
