# Generated by Django 6.0.3 on 2026-05-07 19:13

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_app', '0010_subjectlabroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectlabroom',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable_app.department'),
        ),
        migrations.AddField(
            model_name='subjectlabroom',
            name='semester',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='department', chained_model_field='department', null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable_app.semester'),
        ),
        migrations.AlterField(
            model_name='subjectlabroom',
            name='classroom',
            field=models.ForeignKey(limit_choices_to={'is_lab': True}, on_delete=django.db.models.deletion.CASCADE, to='timetable_app.classroom'),
        ),
        migrations.AlterField(
            model_name='subjectlabroom',
            name='subject',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='semester', chained_model_field='semester', limit_choices_to={'is_lab': True}, on_delete=django.db.models.deletion.CASCADE, to='timetable_app.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='subjectlabroom',
            unique_together={('subject', 'classroom')},
        ),
    ]
