# Generated by Django 6.0.3 on 2026-05-07 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_app', '0011_subjectlabroom_department_subjectlabroom_semester_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectlabroom',
            name='department',
        ),
        migrations.AlterField(
            model_name='subjectlabroom',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable_app.semester'),
        ),
    ]
