# Generated by Django 5.2.11 on 2026-05-12 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_app', '0012_remove_subjectlabroom_department_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subjectlabroom',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='subjectlabroom',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable_app.classroom'),
        ),
        migrations.AlterField(
            model_name='subjectlabroom',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable_app.subject'),
        ),
        migrations.RemoveField(
            model_name='subjectlabroom',
            name='semester',
        ),
    ]
