# Generated by Django 5.2.11 on 2026-05-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_app', '0013_alter_subjectlabroom_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('action_type', models.CharField(choices=[('Department', 'Department'), ('Semester', 'Semester'), ('Faculty', 'Faculty'), ('Subject Faculty', 'Subject Faculty')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
