# Generated by Django 5.2.11 on 2026-05-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_app', '0014_recentactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentactivity',
            name='action_type',
            field=models.CharField(choices=[('Department', 'Department'), ('Semester', 'Semester'), ('Faculty', 'Faculty'), ('Subject', 'Subject'), ('Subject Faculty', 'Subject Faculty'), ('Classroom', 'Classroom'), ('Timing', 'Timing'), ('Generate', 'Generate'), ('Remove', 'Remove'), ('Delete', 'Delete'), ('Edit', 'Edit'), ('Add', 'Add')], default='Add', max_length=100),
        ),
    ]
